constants = {
    'task_name':'grasp_red_box',
    'dataset_root':'dataset',
    'ckpt_root':'checkpoints',
    'num_episodes':60,
    'eval':True,
    'save_per_epoch':100,
    'num_epochs':20000,
    'batch_size_train': 32,
    'batch_size_val': 32,
    'episode_len': 500,
    'kl_weight':10,
    'dim_feedforward':3200,
    'chunk_size':64,
    'state_dim':8,
    'hidden_dim':512,
    'weight_decay': 1e-6,
    'lr': 1e-04,
    'lr_backbone': 1e-04,
    'seed': 0,
    'num_roll_outs': 50,
    'episode_len': 280,
    'onscreen_render': True,
    'onscreen_cam': 'free',
    'temporal_agg': False,
    'observation_horizon': 1,
}
